#server:
#  port: 8150
#spring:
#  mail:
#    host: smtp.qq.com
#    username: 2830429738@qq.com
#    password: tvkepnqikvjbddde
#    default-encoding: UTF-8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    sentinel:
#      transport:
#        port: 8081
#        dashboard: localhost:8080
#  profiles:
#    active: dev
#  application:
#    name: service-sms
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    password:  #默认为空
#    lettuce:
#      pool:
#        max-active: 20  #最大连接数，负值表示没有限制，默认8
#        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
#        max-idle: 8     #最大空闲连接，默认8
#        min-idle: 0     #最小空闲连接，默认0
#aliyun:
#  sms:
#    regionId: cn-hangzhou
#    keyId: LTAI4FvvVEWiTJ3GNJJqJnk7
#    keySecret: 9st82dv7EvFk9mTjYO1XXbM632fRbG
#    templateCode: SMS_210076548
#    signName: 学习短信发送方式
#
